# Generated by Django 4.2.6 on 2023-10-29 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_author_lmsuser_publisher_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_img', models.ImageField(blank=True, null=True, upload_to='books/')),
                ('name', models.CharField(max_length=64, null=True)),
                ('book_con', models.TextField()),
                ('ISBN', models.CharField(max_length=64)),
                ('translator', models.CharField(max_length=64)),
                ('date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='LmssUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publisher',
        ),
        migrations.DeleteModel(
            name='LmsUser',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='author',
            name='author_img',
            field=models.ImageField(blank=True, null=True, upload_to='authors/'),
        ),
        migrations.AddField(
            model_name='publisher',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='publishers/'),
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.AddField(
            model_name='book1',
            name='author',
            field=models.ManyToManyField(to='mysite.author'),
        ),
        migrations.AddField(
            model_name='book1',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.publisher'),
        ),
    ]
