# Generated by Django 4.2.6 on 2023-11-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_book1_lmssuser_remove_book_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book1',
            old_name='book_con',
            new_name='book_con1',
        ),
        migrations.AddField(
            model_name='book1',
            name='book_con2',
            field=models.TextField(default='context'),
        ),
        migrations.AlterField(
            model_name='author',
            name='author_img',
            field=models.TextField(default='author_img'),
        ),
        migrations.AlterField(
            model_name='book1',
            name='book_img',
            field=models.TextField(default='book_img'),
        ),
        migrations.AlterField(
            model_name='book1',
            name='status',
            field=models.CharField(choices=[('館藏中', '館藏中'), ('預約中', '預約中'), ('外借中', '外借中')], default='館藏中', max_length=10),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='img',
            field=models.TextField(default='Publisher_img'),
        ),
    ]
